### ISSUE TITLE
No font support

### ISSUE THREAD

**Issue by ochafik** [openscad/openscad-wasm#3] opened 2022-03-05 14:52 UTC
Now that #2 seems on its way to be fixed, let's get serious!

Any attempt to draw text fails with:

```
Fontconfig error: Cannot load default config file: No such file: (null)
```

[Example](https://tinyurl.com/mvcu7wen)

**Comment by DSchroer** [comment] 2022-03-05 20:00
Fonts can be made to work. The trick is you need to supply the font and fontconfig config file within the `/fonts` directory in the FS. There is an example on how to make it work under the `tests/text` directory.

**Comment by t-paul** [comment] 2022-03-05 20:02
My suggestion would be to provide a preloaded file system with MCAD (as that's shipping with other releases too usually) and the default font (Liberation). I'll try to prepare that if there's no votes against that idea.

**Comment by DSchroer** [comment] 2022-03-05 20:13
That works for me. I would like to adjust a few flags on the build so that we can run the program multiple times on the same FS. That way the loading and initiation can be minimized. I suspect that we will need that if we start adding more resourced baked in.

**Comment by DSchroer** [comment] 2022-03-05 21:18
Now this raises a question. Do we package the fonts as an optional addon or do we use a post build processing step to embed them? Any preferences? 

I prefer the post build approach but it then makes it rather hard to put the build processes back into the OpenSCAD repo in the future.

**Comment by t-paul** [comment] 2022-03-05 21:20
I'm not sure about the technical aspects and limitations, but I'm thinking maybe providing just the bare minimum preloaded and having some way to mount additional file systems for fonts/libraries/... would be nice.

**Comment by DSchroer** [comment] 2022-03-05 21:23
That could work. We can setup some kind of addon system:
```js
import OpenSCAD from "./openscad.js";
import {addFonts} from "./addons.js";

const instance = await OpenSCAD({...});
addFonts(instance);

...
```
How about something that works like that? Kind of an addon library that we can build on.

**Comment by DSchroer** [comment] 2022-03-05 21:25
The other option is to ship a wrapper:
```js
import OpenSCAD from "./openscad.wrapper.js";

const instance = await OpenSCAD();
// has fonts now
...
```

Or to embed it within the wrapper post build:
```js
import OpenSCAD from "./openscad.js";

const instance = await OpenSCAD();
// has fonts now
...
```

**Comment by DSchroer** [comment] 2022-03-05 21:29
Looking at it now I think the first option is best. Create a library that lets the user control what gets tree shaken out.

**Comment by ochafik** [comment] 2022-03-06 18:49
Related: I'm now looking at how to provide libraries inside the playground.

I'm about to try and integrate https://github.com/isomorphic-git/isomorphic-git + https://github.com/jvilk/BrowserFS#using-with-emscripten, so that one can add libraries with just their Git URL & have them picked up by OpenSCAD automatically (and updated automatically / persisted in local storage, and still have a system where one can share a deep link to an example that will work on another browser as it can fetch the same dependencies by cloning them too).

I like the idea of pre-baking some default font + support `addFonts` helper (either accepting the emscripten instance or an FS implementation like BrowserFS). Or, if there's some git repo with fonts, we can also make that available through the same system as libraries (but I'm not sure how fonts are imported, do they need to be in a special folder?)

**Comment by DSchroer** [comment] 2022-03-06 21:31
I think its best to leave this problem open to the implementer. @ochafik you are intending to build essentially a small web IDE so you will need to supply lots of supporting infrastructure. However someone who wants to just build a web based configurator for one model would not want to ship fonts and libs. 

Now I have added a `openscad.runtime.js` project that does a lot of the heavy lifting for you when it comes to embedding things like fonts. It publishes typings files and a single JS file that contains the fonts and logic to load them. It needs lots of optimization (currently 12M) but the idea is there and working. What I want to avoid is shipping a huge project while really this is intended to be the minimum building block to build a web based tool built around OpenSCAD.

If you want to do it yourself just dump the font TTF files and a basic `fonts.conf` file into a `/fonts` directory in the FS. Look at the `addFonts` implementation to see exactly what you need there.

**Comment by DSchroer** [comment] 2022-03-06 21:48
One thing to note is that I would never advise using `openscad.runtime.js` without a tree shaking tool. So I need to think more about how this will eventually be published and consumed. Using it directly will just load too much data into your webpage.

**Comment by DSchroer** [comment] 2022-03-06 22:31
Small change of ideas. In order to remove the need for a tree-shaker and build tooling I think its best to drop the `openscad.runtime.js` idea and use this pattern per feature instead:
```js
import OpenSCAD from "./openscad.js";
import { addFonts } from "./openscad.fonts.js";

const instance = await OpenSCAD({ noInitialRun: true });
addFonts(instance);
```

So each "bundle" of pre-packaged resources could have its own `openscad.XXXX.js` file with whatever assets bundled within it or logic to load them. To me this seems much more scalable over time. 

I have gone ahead and dropped the `runtime` file and am using this pattern instead now.

**Comment by DSchroer** [comment] 2022-03-12 17:58
@ochafik wrapping up this setup. Does this format of addons work for you? Its all in the "web dev" world but should be quite possible to extend this process to fit your need.

**Comment by DSchroer** [comment] 2022-03-13 15:14
@t-paul I went ahead and added MCAD as well. Likely I will stop here because the user of the lib should be able to supply any tooling they need in the environment it is running in. There is a test to validate it as well. So I can confirm that MCAD gears are working as expected. 

Adding MCAD works as follows:
```js
import OpenSCAD from "./openscad.js";
import { addMCAD } from "./openscad.mcad.js";

const instance = await OpenSCAD({ noInitialRun: true });
addMCAD(instance);
```

**Comment by t-paul** [comment] 2022-03-13 16:31
Nice! I agree that the default should be limited to some small baseline and leave it to (developer-) users to extend. MCAD and the default font seems like a good base.

Packaging libraries is a topic for native OpenSCAD aswell, so maybe we can find some solution that works for both scenarios. But I certainly see that as separate from the main build, and @ochafik already has proven that it's possible to do by including a list of libraries.

**Comment by ochafik** [comment] 2022-03-16 10:31
@t-paul I've now also included MCAD in https://ochafik.com/openscad btw.

@DSchroer re/ fonts, I've opted to have BrowserFS mount a zip with all the fonts (+ and the font config) instead of using `addFonts`, consistent with the other library assets (see [here](https://github.com/ochafik/openscad-wasm/blob/editor-ochafik.com/example/www/filesystem.js)). This requires just to have the byte arrays of the zips in memory and access is otherwise lazy.

**Comment by t-paul** [comment] 2022-03-16 17:16
I think it might be nice to have the mini-modules available for use in the default build (Liberation fonts + MCAD) with prepration for including additional external stuff view BrowserFS.

It would be nice if the default build could be ready to use for statically sharing designs. Any further extensions could live as separate projects based on the base build. Does that make sense?

**Comment by DSchroer** [comment] 2022-03-16 18:26
I 100% agree with your vision of statically sharing designs. I am less and less convinced that it should be in the default build though. I think the default really should be just the wasm+js that is the minimum to get it working. Then another tool can be built around it that makes it easy to statically share designs and such. That way this project scales nicely without committing to too much.  

I am working on a static configurator project as well and the more I work on it I am rebuilding parts in this repo because they dont match the needs. To me that indicates that we might need to scale the scope back a bit here.

**Comment by DSchroer** [comment] 2022-03-20 19:13
Closing this issue as support for fonts and mcad have been added.

**Closed as completed by DSchroer** 2022-03-20 19:13 UTC

**Comment by joeskeen** [comment] 2023-07-02 20:48
Apologies for putting this here, but as @ochafik doesn't have issues enabled on his fork, I'm wondering what fonts are available at <https://ochafik.com/openscad>? I've tried a handful and none of them seem to work.

**Comment by t-paul** [comment] 2023-07-02 21:03
@joeskeen the font archive served from `https://ochafik.com/openscad/libraries/fonts.zip` has
```
$ unzip -l  fonts.zip 
Archive:  fonts.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      122  2023-03-21 23:10   fonts.conf
   301684  2023-03-21 23:10   LiberationMono-Bold.ttf
   277912  2023-03-21 23:10   LiberationMono-BoldItalic.ttf
   274984  2023-03-21 23:10   LiberationMono-Italic.ttf
   313408  2023-03-21 23:10   LiberationMono-Regular.ttf
   353936  2023-03-21 23:10   LiberationSans-Bold.ttf
   349724  2023-03-21 23:10   LiberationSans-BoldItalic.ttf
   355608  2023-03-21 23:10   LiberationSans-Italic.ttf
   350200  2023-03-21 23:10   LiberationSans-Regular.ttf
   365112  2023-03-21 23:10   LiberationSerif-Bold.ttf
   371060  2023-03-21 23:10   LiberationSerif-BoldItalic.ttf
   370968  2023-03-21 23:10   LiberationSerif-Italic.ttf
   388352  2023-03-21 23:10   LiberationSerif-Regular.ttf
     4414  2023-03-21 23:10   LICENSE
      242  2023-03-21 23:10   AUTHORS
---------                     -------
  4077726                     15 files
```
Note that more recent work went into https://ochafik.com/openscad2/ which is hosted at https://github.com/openscad/openscad-playground
